### ISSUE TITLE
Context

### ISSUE THREAD

**Issue by billinghamj** [mrz1836/postmark#22]
How should context/ctx be passed into method calls like `SendEmail`? I'm not seeing any docs or obvious way that could be done, but possible I'm missing something

Use of context is quite standard for Go applications & libraries since it was added to the standard library in 2016 (Go 1.7). It's key to being able to do things like graceful shutdown, handling timeouts, cancelling requests etc.

Notably, context should never be persisted or stored - only passed along/used ephemerally with method calls

**Comment by billinghamj** [comment]
@mrz1836 From having had a very cursory look at the code, currently I think it probably always uses the background context

Go functions accept context as their first parameter, but that would mean changing the signatures of virtually all functions in the package. I assume you'd want to avoid breaking changes or needing a new major version?

**Comment by billinghamj** [comment]
I'll pop in a PR with a change like that, then can see if you like it :)

**Comment by billinghamj** [comment]
#23

I did also notice that API errors don't seem to be handled - the `StatusCode` of the `*http.Response` isn't checked, but that might be best considered separately!

**Comment by billinghamj** [comment]
Nice, thank you!

**Comment by ChristianSch** [comment]
It would've been cool though if this was a major version bump, as it includes breaking changes ;)
See [here](https://semver.org/):
> Given a version number MAJOR.MINOR.PATCH, increment the:
>
>   MAJOR version when you make incompatible API changes

**Comment by billinghamj** [comment]
Unfortunately, for Go libraries, major version changes are a bit of a nightmare, as most of the standard tooling does not help people update - largely treating them as separate libraries, meaning the original basically needs to be supported forever

For a change like this, which can be adapted to very easily and which cannot cause unexpected behaviour (due to preventing compilation with old code), it may be the lesser evil

Would be good if Go handled major changes differently to make this kind of change less of a difficult decision
