### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by shubham1172** [mrz1836/postmark#6]
**What's your question?**
I see that you have a MIT license badge in the README, but the LICENSE file says otherwise. Can you please clarify on the license and if possible, update the LICENSE file to reflect the same?

**Comment by mrz1836** [comment]
The license is from the original repo. From what I can tell, it looks like an MIT license.

@shubham1172  If you feel it's not a MIT license, can you clarify how/why?

**Comment by shubham1172** [comment]
@mrz1836, MIT licenses usually start with the text
```
The MIT License (MIT)
```
For example, https://github.com/vuejs/vue/blob/dev/LICENSE

Also, the LICENSE file has different text than from standard MIT licenses - https://opensource.org/licenses/MIT. The main thing that seems to be missing is the following:
```
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without 
limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do so, 
subject to the following conditions:
```

On using a standard MIT license, GitHub also shows this header:
![image](https://user-images.githubusercontent.com/22132944/152559496-f694afe2-5ec6-4b2e-bc26-ce36b54a6e06.png)

If this is meant to be a MIT license, should we update the LICENSE file with the standard MIT text?

**Comment by mrz1836** [comment]
I see that, thank you for making it clear. 👍 

That was "their" original license. I don't see it being restrictive, but you are correct, it's not 100% MIT.

Going forward, I could change the license in this fork to be more specific that it is a MIT license.

If you want to create a PR with the changes - we can review and merge it in.

**Comment by shubham1172** [comment]
Thanks @mrz1836, I will create a PR!

**Comment by shubham1172** [comment]
Thank you for your quick help, @mrz1836!
